name: Build and Publish iTop Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push images
      run: |
        while IFS= read -r line; do
          if [[ $line == *"itop_version:"* ]]; then
            itop_version=$(echo $line | awk '{print $2}' | tr -d '"')
            echo "Found iTop version: $itop_version"
          elif [[ $line == *"php_version:"* ]]; then
            php_version=$(echo $line | awk '{print $2}' | tr -d '"')
            echo "Found PHP version: $php_version"
          elif [[ $line == *"url:"* ]]; then
            url=$(echo $line | awk '{print $2}' | tr -d '"')
            echo "Found URL: $url"
            echo "Building Docker image..."
            docker build \
              --build-arg PHP_VERSION=$php_version \
              --build-arg ITOP_URL=$url \
              -t ${{ secrets.DOCKERHUB_USERNAME }}/itop:${itop_version}-php${php_version} .
            echo "Pushing Docker image..."
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/itop:${itop_version}-php${php_version}
            echo "Image pushed successfully"
          fi
        done < itop-versions.yml